### ISSUE TITLE
Unable to perform a migration with SQLite and unable to use MySQL

### ISSUE THREAD

**Issue by gusandrianos** [pagojo/rethoth#1]
I try to do a `thoth migrate` and it throws a 
`Mysql2::Error: Table 'thoth.posts' doesn't exist (Sequel::DatabaseError)` error
or a
`SQLite3::SQLException: no such table: posts (Sequel::DatabaseError)` error.

With MySQL you have to manually create the database, a db migrate won't do it for you. SQLite obviously has a db file but the table issue remains.

My setup is.
Ubuntu Gnome 16.04.2, kernel 4.8.0-56-generic.
I have the latest versions of ruby, rvm, MySQL and SQLite.

I've heard that some successfully completed the steps for setup but they were on Mac, maybe it's a Linux specific issue.

**Comment by pagojo** [comment]
Hi :-)

So you are saying that even when you change the code to load the ```mysql2``` adaptor, it still doesn't complete the ```thoth migrate``` step right?

Before we figure out MySQL, can you please confirm that it doesn't work at all with Sqlite3?

Preferably post here all the steps you take on the command line and a list of all the gems installed in your setup.

**Comment by gusandrianos** [comment]
**Steps**
thoth --create testP
`Your new Thoth home directory has been created at /home/gus/Desktop/testP`
cd testP/
thoth migrate
```
/home/gus/.rvm/gems/ruby-2.4.1/gems/rethoth-0.4.1/lib/thoth/controller/comment.rb loaded
/home/gus/.rvm/gems/ruby-2.4.1/gems/rethoth-0.4.1/lib/thoth/controller/search.rb loaded
/home/gus/.rvm/gems/ruby-2.4.1/gems/rethoth-0.4.1/lib/thoth/controller/tag.rb loaded
/home/gus/.rvm/gems/ruby-2.4.1/gems/rethoth-0.4.1/lib/thoth/controller/archive.rb loaded
/home/gus/.rvm/gems/ruby-2.4.1/gems/rethoth-0.4.1/lib/thoth/controller/api loaded
/home/gus/.rvm/gems/ruby-2.4.1/gems/rethoth-0.4.1/lib/thoth/controller/post.rb loaded
/home/gus/.rvm/gems/ruby-2.4.1/gems/rethoth-0.4.1/lib/thoth/controller/media.rb loaded
/home/gus/.rvm/gems/ruby-2.4.1/gems/rethoth-0.4.1/lib/thoth/controller/page.rb loaded
/home/gus/.rvm/gems/ruby-2.4.1/gems/rethoth-0.4.1/lib/thoth/controller/admin.rb loaded
/home/gus/.rvm/gems/ruby-2.4.1/gems/rethoth-0.4.1/lib/thoth/controller/main.rb loaded
/home/gus/.rvm/gems/ruby-2.4.1/gems/rethoth-0.4.1/lib/thoth/controller/api/comment.rb loaded
/home/gus/.rvm/gems/ruby-2.4.1/gems/rethoth-0.4.1/lib/thoth/controller/api/tag.rb loaded
/home/gus/.rvm/gems/ruby-2.4.1/gems/rethoth-0.4.1/lib/thoth/controller/api/post.rb loaded
/home/gus/.rvm/gems/ruby-2.4.1/gems/rethoth-0.4.1/lib/thoth/controller/api/page.rb loaded
SEQUEL DEPRECATION WARNING: Setting a model class dataset to an invalid dataset is deprecated and will be removed in Sequel 5.  Either use a valid dataset or set require_valid_table = false for the model class.
/home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/model/base.rb:992:in `rescue in check_non_connection_error'
/home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/model/base.rb:985:in `check_non_connection_error'
/home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/model/base.rb:1106:in `block in get_db_schema'
/home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/model/base.rb:1139:in `get_db_schema'
/home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/model/base.rb:878:in `set_dataset'
/home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/model/base.rb:689:in `inherited'
/home/gus/.rvm/gems/ruby-2.4.1/gems/rethoth-0.4.1/lib/thoth/model/comment.rb:33:in `<module:Thoth>'
/home/gus/.rvm/gems/ruby-2.4.1/gems/rethoth-0.4.1/lib/thoth/model/comment.rb:32:in `<top (required)>'
/home/gus/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/gus/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/gus/.rvm/gems/ruby-2.4.1/gems/rethoth-0.4.1/lib/thoth/model/comment.rb loaded
SEQUEL DEPRECATION WARNING: Setting a model class dataset to an invalid dataset is deprecated and will be removed in Sequel 5.  Either use a valid dataset or set require_valid_table = false for the model class.
/home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/model/base.rb:992:in `rescue in check_non_connection_error'
/home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/model/base.rb:985:in `check_non_connection_error'
/home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/model/base.rb:1106:in `block in get_db_schema'
/home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/model/base.rb:1139:in `get_db_schema'
/home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/model/base.rb:878:in `set_dataset'
/home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/model/base.rb:689:in `inherited'
/home/gus/.rvm/gems/ruby-2.4.1/gems/rethoth-0.4.1/lib/thoth/model/tag.rb:30:in `<module:Thoth>'
/home/gus/.rvm/gems/ruby-2.4.1/gems/rethoth-0.4.1/lib/thoth/model/tag.rb:29:in `<top (required)>'
/home/gus/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/gus/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/gus/.rvm/gems/ruby-2.4.1/gems/rethoth-0.4.1/lib/thoth/model/tag.rb loaded
SEQUEL DEPRECATION WARNING: Setting a model class dataset to an invalid dataset is deprecated and will be removed in Sequel 5.  Either use a valid dataset or set require_valid_table = false for the model class.
/home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/model/base.rb:992:in `rescue in check_non_connection_error'
/home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/model/base.rb:985:in `check_non_connection_error'
/home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/model/base.rb:1106:in `block in get_db_schema'
/home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/model/base.rb:1139:in `get_db_schema'
/home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/model/base.rb:878:in `set_dataset'
/home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/model/base.rb:689:in `inherited'
/home/gus/.rvm/gems/ruby-2.4.1/gems/rethoth-0.4.1/lib/thoth/model/post.rb:30:in `<module:Thoth>'
/home/gus/.rvm/gems/ruby-2.4.1/gems/rethoth-0.4.1/lib/thoth/model/post.rb:29:in `<top (required)>'
/home/gus/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/gus/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/gus/.rvm/gems/ruby-2.4.1/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `initialize': SQLite3::SQLException: no such table: posts (Sequel::DatabaseError)
	from /home/gus/.rvm/gems/ruby-2.4.1/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `new'
	from /home/gus/.rvm/gems/ruby-2.4.1/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `prepare'
	from /home/gus/.rvm/gems/ruby-2.4.1/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:264:in `query'
	from /home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/adapters/sqlite.rb:193:in `block (2 levels) in _execute'
	from /home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/database/logging.rb:45:in `log_connection_yield'
	from /home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/adapters/sqlite.rb:193:in `block in _execute'
	from /home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/database/connecting.rb:301:in `block in synchronize'
	from /home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/connection_pool/threaded.rb:107:in `hold'
	from /home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/database/connecting.rb:301:in `synchronize'
	from /home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/adapters/sqlite.rb:186:in `_execute'
	from /home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/adapters/sqlite.rb:131:in `execute'
	from /home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/dataset/actions.rb:1073:in `execute'
	from /home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/adapters/sqlite.rb:335:in `fetch_rows'
	from /home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/dataset/actions.rb:934:in `with_sql_each'
	from /home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/dataset/actions.rb:942:in `with_sql_first'
	from /home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/dataset/actions.rb:950:in `with_sql_single_value'
	from /home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/dataset/actions.rb:770:in `single_value!'
	from /home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/dataset/actions.rb:109:in `count'
	from /home/gus/.rvm/gems/ruby-2.4.1/gems/sequel-4.47.0/lib/sequel/model/plugins.rb:33:in `count'
	from /home/gus/.rvm/gems/ruby-2.4.1/gems/rethoth-0.4.1/lib/thoth/model/post.rb:250:in `<module:Thoth>'
	from /home/gus/.rvm/gems/ruby-2.4.1/gems/rethoth-0.4.1/lib/thoth/model/post.rb:29:in `<top (required)>'
	from /home/gus/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/gus/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/gus/.rvm/gems/ruby-2.4.1/gems/rethoth-0.4.1/lib/thoth.rb:84:in `block (2 levels) in acquire'
	from /home/gus/.rvm/gems/ruby-2.4.1/gems/rethoth-0.4.1/lib/thoth.rb:83:in `each'
	from /home/gus/.rvm/gems/ruby-2.4.1/gems/rethoth-0.4.1/lib/thoth.rb:83:in `block in acquire'
	from /home/gus/.rvm/gems/ruby-2.4.1/gems/rethoth-0.4.1/lib/thoth.rb:82:in `each'
	from /home/gus/.rvm/gems/ruby-2.4.1/gems/rethoth-0.4.1/lib/thoth.rb:82:in `acquire'
	from /home/gus/.rvm/gems/ruby-2.4.1/gems/rethoth-0.4.1/lib/thoth.rb:239:in `init_thoth'
	from /home/gus/.rvm/gems/ruby-2.4.1/gems/rethoth-0.4.1/lib/thoth.rb:284:in `run'
	from /home/gus/.rvm/gems/ruby-2.4.1/gems/rethoth-0.4.1/bin/thoth:225:in `<module:Thoth>'
	from /home/gus/.rvm/gems/ruby-2.4.1/gems/rethoth-0.4.1/bin/thoth:34:in `<top (required)>'
	from /home/gus/.rvm/gems/ruby-2.4.1/bin/thoth:22:in `load'
	from /home/gus/.rvm/gems/ruby-2.4.1/bin/thoth:22:in `<main>'
	from /home/gus/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/gus/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'


```

**Comment by gusandrianos** [comment]
Gems installed.

Latest bundler
Latest Ruby and sqlite3.
Whatever rethoth installed as a dependency
:)

**Comment by pagojo** [comment]
Can you please ```gem list```
and ```rvm info```

**Comment by pagojo** [comment]
ohhh just noticed @GusAndrianos you didn't do ```thoth --migrate``` you forgot the ```--```

**Comment by gusandrianos** [comment]
Seems like you did too, it's not like that in the ReadMe. :+1: 
Now it works.

**Comment by pagojo** [comment]
Does it work with MySQL as well, without any patch?

**Comment by gusandrianos** [comment]
It does not.
![screenshot from 2017-07-04 22-05-18](https://user-images.githubusercontent.com/17255848/27840818-ec0b0a96-6104-11e7-8d38-f98a9d5574ba.png)

With the patch in my PR, it finds MySQL, but, it cannot complete the migration.
The first error it throws is.
![screenshot from 2017-07-04 22-09-11](https://user-images.githubusercontent.com/17255848/27840883-714d858a-6105-11e7-8f42-890d3aa23717.png)

And if I manually create the db, it throws this.
![screenshot from 2017-07-04 22-10-06](https://user-images.githubusercontent.com/17255848/27840902-9114b730-6105-11e7-9a75-ff8c8e9d6b0d.png)

**Comment by pagojo** [comment]
ok, then this should be opened as an independent issue then. Can you do this please?

**Comment by gusandrianos** [comment]
Will do :)
